export const ABRIR_FORMULARIO_CREAR_MATERIA_CARRERA = 'abrir_formulario_crear_materia_carrera'

export const CERRAR_FORMULARIO_MATERIA_CARRERA = 'cerrar_formulario_materia_carrera'

export const CREAR_MATERIA_CARRERA_REQUEST = 'crear_materia_carrera_request'
export const CREAR_MATERIA_CARRERA_EXITO = 'crear_materia_carrera_exito'
export const CREAR_MATERIA_CARRERA_FALLO = 'crear_materia_carrera_fallo'

export const ABRIR_FORMULARIO_EDITAR_MATERIA_CARRERA_REQUEST = 'abrir_formulario_editar_materia_carrera_request'
export const ABRIR_FORMULARIO_EDITAR_MATERIA_CARRERA_EXITO = 'abrir_formulario_editar_materia_carrera_exito'
export const ABRIR_FORMULARIO_EDITAR_MATERIA_CARRERA_FALLO = 'abrir_formulario_editar_materia_carrera_fallo'

	export const EDITAR_MATERIA_CARRERA_REQUEST = 'editar_materia_carrera_request'
	export const EDITAR_MATERIA_CARRERA_EXITO = 'editar_materia_carrera_exito'
	export const EDITAR_MATERIA_CARRERA_FALLO = 'editar_materia_carrera_fallo'

export const ELIMINAR_MATERIA_CARRERA_REQUEST = 'eliminair_materia_carrera_request'
export const ELIMINAR_MATERIA_CARRERA_EXITO = 'eliminair_materia_carrera_exito'
export const ELIMINAR_MATERIA_CARRERA_FALLO = 'eliminair_materia_carrera_fallo'
